name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: make build

      - name: Lint content
        run: make lint

      - name: Build blog
        run: make build_blog
